export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const HOMEPAGE_ROUTE = '/'
export const SHOP_ROUTE = '/store'
export const PROFILE_ROUTE ='/profile'
export const HISTORY_ROUTE ='/history'
export const ENGINE_ROUTE = '/engine'